app = "graphql-react-examples"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  [[services.tcp_checks]]
    grace_period = "8s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
